### ISSUE TITLE
Expectation of an observed variable

### ISSUE THREAD

**Issue by owiecc** [SciML/DiffEqUncertainty.jl#53]
I have a system made using ModelingToolkit that contains some observed variables. Can I extract the expectation of one of these observed variables in some way? 

My two ideas on how to do it: 
1. Pull out the relationship between the observed variable and the state vector and plug that code directly to the expectation function. 
2. Force the observed variable into the state vector in ModelingToolkit after the `structural_simplify` step. 

Is there a better way?

**Comment by owiecc** [comment]
You mean this:
```julia
g(sol) = sol(10.0)[resistor.V]
```
I can see this works in the [tutorial](https://tutorials.sciml.ai/html/DiffEqUncertainty/01-expectation_introduction.html):
```julia
g(sol) = [sol(4.0)[1], sol(6.0)[1]]
```
but this operates only on the state vector. 

I will try to implement that. I am having some issues now with Quadrature and stuff does not work.

**Comment by owiecc** [comment]
I guess this is more of a question about the DifferentialEquations.jl interface. This code
```julia
g(sol) = sol[Resistor.v]
```
does indeed return a vector of resistor voltages. I cannot, however, see an option to ask for the resistor voltage at time `t=10.0`. Is my only option 
```julia
tend = 10.0
prob = ODAEProblem(sys, u0, (0, tend))
g(sol) = sol[resistor.V]
vR = expectation(g, prob, u0_dist, p, Koopman(), Tsit5()).u[end]
```
or is there a way I can mix time and variable in the expectation function? Something like
```julia
g(sol) = sol(10.0)[resistor.V]
```

**Comment by ChrisRackauckas** [comment]
Yeah, I want to make this work with `sol(10.0,idxs=:resistor.V)` but that won't for now https://github.com/SciML/SciMLBase.jl/issues/13 . The right thing to do right now would be to do

```julia
vR = expectation(g, prob, u0_dist, p, Koopman(), Tsit5(), saveat = [10.0]).u[end]
```

and then just index it. I'll close because the remaining issue, interpolation of observed variables, is its own ordeal.
