### ISSUE TITLE
Does the Quadrature.jl/Integrals.jl dependency version spec need to be upgraded?

### ISSUE THREAD

**Issue by txn2022** [SciML/DiffEqUncertainty.jl#62]
I got a strange situation with versions of DiffEqUncertainty and Quadrature packages (https://stackoverflow.com/questions/72794683/strange-behavior-of-diffequncertainty-jl-and-quadrature-jl). The guess for this situation is that the DiffEqUncertainty package declares its dependency as Quadrature major version 1, meanshile the current version of Quadrature pacakage is 2.1 already.

Does the Quadrature.jl/Integrals.jl dependency version spec need to be upgraded?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqUncertainty.jl/pull/63
